package i.co.Exception;

public class CatchEx {
	
	
	public static void main(String[] args) {
	// single catch
		
		
		int i= 0;
		int j= 20;
		 double v = i*j;
		 
	}}
	    
		/*try {
			 int value = j/i;
			 System.out.println(value);
		}catch (Exception e) {
			// TODO: handle exception
		
		  System.out.println("divided by zero");
		  e.printStackTrace();
		  System.out.println(e.getMessage());
		}finally {
			System.out.println("finally block");
		}
  		 
		
	*/